# Site settings and it builds from main branch
title: JBossWS
email:
meta_author: jbossws
# Build settings
markdown: kramdown
parse_block_html: true
permalink: pretty
paginate: 15
paginate_path: "blogs/page:num"
collections:
  guide:
    output: true
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  mkdir: false
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed, jekyll-asciidoc]
plugins: [jekyll-paginate, jekyll-asciidoc]

