name: Build GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout github io
        uses: actions/checkout@v2

      - name: Checkout latest snapshot adoc and image files
        uses: actions/checkout@v2
        with:
          repository: jbossws/jbossws-cxf
          path: './adoc'
      - name: copy snapshot adoc files to github pages
        working-directory: ./adoc
        run: |
          cp -R ./modules/dist/src/main/doc/adoc/content ../jbossws.github.io/_guide/5.5.1-SNAPSHOT
          cp -R ./modules/dist/src/main/doc/adoc/image ../jbossws.github.io/_guide/5.5.1-SNAPSHOT
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build Jekyll site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: false
          prettier_ignore: '*'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site